apiVersion: v1
kind: Secret
metadata:
  name: appsecret
type: Opaque
data:
  WSGSITENAME: {{ .Values.global.WSGSITENAME_BASE64 }} 
  WSGSERVER: {{ .Values.global.WSGSERVER_BASE64 }} 
  WGDBSERVER: {{ .Values.global.WGDBSERVER_BASE64 }} 
  WGDBNAME: {{ .Values.global.WGDBNAME_BASE64 }} 
  WGDBUSER: {{ .Values.global.WGDBUSER_BASE64 }} 
  WGDBPASSWORD: {{ .Values.global.WGDBPASSWORD_BASE64 }}